AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Resources:
  LambdaFunctionOverHttp:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: dist
      Handler: application.lambda_handler
      Runtime: python3.9
      Timeout: 5
      Events:
        HttpPost:
          Type: Api
          Properties:
            Path: $default
            Method: GET, POST